### ISSUE TITLE
WIP: Add option tenant ID for oauth2 source

### ISSUE THREAD

**Issue by Adito5393** [s-hamann/ansible-gitea#1]
There is another CLI flag option (`--custom-tenant-id`) for the custom OAuth2 auth source. 
See https://github.com/go-gitea/gitea/pull/22769.

Once Gitea is released with the patch, could you add support for it?

**Comment by s-hamann** [comment]
Yes, adding that option certainly seems doable. I'm can't promise *when* I'll get around to it, but probably in a timely manner. Do you know when this will hit a released version of Gitea? 1.19?

**Comment by Adito5393** [comment]
I don't know for sure. Hopefully, the next patch release. I'll ping you here if/when I see it live.
Thanks for the support!

**Comment by Adito5393** [comment]
The new CLI option will be part of the future v1.18 release (https://github.com/go-gitea/gitea/pull/23263)
I didn't know that I have to do the backport 🤦
